"""
Generates a downloadable PDF risk report summarizing the flagged clauses
for a contract. Uses reportlab (pure Python, no system dependencies), which
keeps the Docker image small and avoids licensing/binary issues.
"""

import tempfile

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

SEVERITY_COLORS = {
    "HIGH": colors.HexColor("#c0392b"),
    "MEDIUM": colors.HexColor("#d68910"),
    "LOW": colors.HexColor("#7d8c8d"),
}


def generate_pdf_report(
    contract_filename: str,
    overall_score: float,
    risk_level: str,
    clauses: list,
    total_clauses_scanned: int,
) -> str:
    """
    Builds the PDF report and returns the local file path of the generated file.
    """
    tmp_path = tempfile.mktemp(suffix=".pdf")

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], textColor=colors.HexColor("#1a2530")
    )
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]
    body_style.leading = 14

    doc = SimpleDocTemplate(tmp_path, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    story = []

    story.append(Paragraph("ClauseGuard Contract Risk Report", title_style))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph(f"Document analyzed: {contract_filename}", body_style))
    story.append(
        Paragraph(f"Clauses scanned: {total_clauses_scanned}", body_style)
    )
    story.append(Spacer(1, 0.3 * cm))

    level_color = SEVERITY_COLORS.get(risk_level, colors.black)
    summary_style = ParagraphStyle(
        "Summary", parent=styles["Heading1"], textColor=level_color, fontSize=18
    )
    story.append(
        Paragraph(f"Overall Risk Score: {overall_score:.1f} / 100 &nbsp;&mdash;&nbsp; {risk_level}", summary_style)
    )
    story.append(Spacer(1, 0.6 * cm))

    if not clauses:
        story.append(
            Paragraph(
                "No high-risk clause patterns were detected by the automated scan. "
                "This does not replace review by a qualified professional.",
                body_style,
            )
        )
    else:
        story.append(Paragraph("Flagged Clauses", heading_style))
        story.append(Spacer(1, 0.2 * cm))

        table_data = [["#", "Category", "Severity", "Clause excerpt"]]
        for clause in clauses:
            excerpt = clause["clause_text"][:180] + (
                "..." if len(clause["clause_text"]) > 180 else ""
            )
            table_data.append(
                [
                    str(clause["clause_index"] + 1),
                    clause["category"].replace("_", " ").title(),
                    clause["severity"],
                    excerpt,
                ]
            )

        table = Table(table_data, colWidths=[1.2 * cm, 4 * cm, 2.3 * cm, 9.5 * cm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2530")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f6f6")]),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 0.6 * cm))

        story.append(Paragraph("Explanations", heading_style))
        for clause in clauses:
            label = clause["category"].replace("_", " ").title()
            story.append(
                Paragraph(
                    f"<b>#{clause['clause_index'] + 1} — {label} ({clause['severity']}):</b> "
                    f"{clause['explanation']}",
                    body_style,
                )
            )
            story.append(Spacer(1, 0.15 * cm))

    story.append(Spacer(1, 0.6 * cm))
    story.append(
        Paragraph(
            "Disclaimer: This report is generated by an automated pattern-matching "
            "tool for informational purposes only and does not constitute legal "
            "advice. Consult a qualified attorney before making decisions based on "
            "this contract.",
            ParagraphStyle("Disclaimer", parent=body_style, fontSize=8, textColor=colors.grey),
        )
    )

    doc.build(story)
    return tmp_path
